package com.xuhe.platform.dal.mapper;

import com.xuhe.platform.dal.model.SysMenu;
import java.util.List;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Thu Jun 06 21:12:31 CST 2019
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Thu Jun 06 21:12:31 CST 2019
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Thu Jun 06 21:12:31 CST 2019
     */
    SysMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Thu Jun 06 21:12:31 CST 2019
     */
    List<SysMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Thu Jun 06 21:12:31 CST 2019
     */
    int updateByPrimaryKey(SysMenu record);
}