package com.xuhe.platform.dal.mapper;

import com.xuhe.platform.dal.model.SysUser;
import com.xuhe.platform.entity.query.RoleQuery;
import com.xuhe.platform.entity.query.UserQuery;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jun 06 21:12:32 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jun 06 21:12:32 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jun 06 21:12:32 CST 2019
     */
    SysUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jun 06 21:12:32 CST 2019
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jun 06 21:12:32 CST 2019
     */
    int updateByPrimaryKey(SysUser record);


    List<SysUser> findUserList(UserQuery userQuery);
}