server:
  port: 8088
spring:
  profiles:
    active: dev


logging:
  path: logs
  file: xuhedemo


mysql:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mapperLocations: classpath*:/mybatis/**/**Mapper.xml
    configLocation: classpath:/mybatis-config.xml
    order:
      url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=true&autoReconnect=true&allowMultiQueries=true
      username: root
      password: mysql123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池最小值、最大致、初始值
      minIdle: 5
      maxActive: 20
      initialSize: 10
      #借出连接最长期限，如果超时，则连接池会抛出异常  这里配置1分钟
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒  这里配置1分钟
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒 这个里配置5分钟
      minEvictableIdleTimeMillis: 300000
      #用来验证数据库连接的查询语句
      validationQuery: select 'x'
      #执行检查语句超时时间
      validationQueryTimeout: 60000
      #在检查空闲连接是，同时检测连接的可用性
      testWhileIdle: true
      #在连接初始化时，同时检查连接可用性
      testOnConnect: true
      #在借出连接时，同时检查连接可用性 这个可能会降低性能
      testOnBorrow: true
      #在客户端归还连接池，同时检查可用性 这个可能会降低性能
      testOnReturn: true







